### ISSUE TITLE
ubuntu 16.04 - mem dump written (static)

### ISSUE THREAD

**Issue by LocutusOfPenguin** [elcabesa/vajolet#1]
Hi,
if i use the standard makefile the resulting vajolet2.exe prints your info line (author), and crushes with mem-dump.
If i remove the "-static" from makefile, the resulting file works.
Despite this, i would guess most users prefer a dyn linked program :-)

Also i would like to propose to include *.d, *.o files in gitignore file (see: git status after compile)

pressing " Carriage Return " starts a new search. Perhaps just ignore invalid user input?
Jürgen

**Comment by LocutusOfPenguin** [comment]
for second (gitignore) something like this added:

*.[oad]
*~
cmake-build-debug
.idea

**Comment by elcabesa** [comment]
hi Jürgen,
I know about the problem of static build on linux, I'll remove the flag from the makefile as soon as possbile. The biggest problem is that on windows it work well with static flag.
regarding carriage return I'll try to solve the problem.

**Comment by LocutusOfPenguin** [comment]
Hi Marco,
thanks.
concerning the " cr " , i see that this seems to resend the last command, if i type "uci"  "cr" the uci seems to be resend.

**Comment by elcabesa** [comment]
the second problem is fixed (uci and carriage return)

**Comment by elcabesa** [comment]
fixed in https://github.com/elcabesa/vajolet/commit/a0f1a79f2c9a77e102d1adcc01f58c69ce56705c

**Comment by LocutusOfPenguin** [comment]
thx!
but it was 3rd :-) cause second is "gitignore" , which y not done...But its not that important, ha

I included vajolet in (my) project "picochess" already, but i had to remove the "-msse4.2 -mpopcnt" and fix the tbcore.c
(see http://talkchess.com/forum/viewtopic.php?topic_view=threads&p=738162&t=65682)
to make it work on RaspPi (main target for picochess)

Jürgen
