### ISSUE TITLE
Windows 64 bit binaries without bmi2-option

### ISSUE THREAD

**Issue by yellow-panther** [elcabesa/vajolet#26]
Could you create such win64-binaries for older computers with no Haswell microarchitecture please?
https://en.wikipedia.org/wiki/Bit_Manipulation_Instruction_Sets

**Comment by elcabesa** [comment]
Hi, usually I create builds without bmi instruction set. you can find them in release 2.6 and 2.6.1 of Vajolet
vajolet 2.6.2 is a small bugfix with not so much differences from 2.6.1 and it was mainly odne for TCEC and CCC. there is almost no difference from Vajolet 2.6.1
