### ISSUE TITLE
Vajolet2-2.5 for android

### ISSUE THREAD

**Issue by Alexei1981** [elcabesa/vajolet#3]
Hello. I'm porting the engines to android and recently made the version of Vajolet2-2.4 (32 and 64 bit) for the arm platform and they work fine. But with the new version of Vajolet2-2.5 there are problems. If the version for 32 bits still works (although not in all GUI) then the version for arm64v8 (64 bit) works badly. When exiting the debut book, it makes an illegal move and everything, the game is finished. It makes it both white and black. What is the problem? For android, the source for Linux is ideal. You can do this do I fix it? Thanks.

**Comment by Alexei1981** [comment]
I ran the engine through the android terminal and that's how it showed the error of the engine (it works fine, but when you need to make a move it makes a mistake):
$ Vajolet2-2.5-arm64v8
Vajolet2 2.5 by Marco Belli
go depth 13
info depth 1
info multipv 1 depth 1 seldepth 1 score cp 58 nodes 23 nps 23000 time 1 pv d2d3
info depth 2
info multipv 1 depth 2 seldepth 2 score cp 58 nodes 26 nps 26000 time 1 pv d2d3 b8a6
info depth 3
info multipv 1 depth 3 seldepth 3 score cp -41 nodes 68 nps 68000 time 1 pv d2d3 b8a6 e1d2
info multipv 1 depth 3 seldepth 3 score cp 7 nodes 103 nps 51500 time 2 pv b1c3 b8c6 a1b1 info multipv 1 depth 3 seldepth 6 score cp 25 nodes 198 nps 66000 time 3 pv e2e3 e7e6 g1f3
info depth 4
info multipv 1 depth 4 seldepth 4 score cp -174 nodes 227 nps 75666 time 3 pv e2e3 e7e6 g1f3 b8c6
info multipv 1 depth 4 seldepth 4 score cp -161 nodes 246 nps 82000 time 3 pv g1f3 b8c6 h1g1 d7d6
info multipv 1 depth 4 seldepth 4 score cp -160 nodes 266 nps 66500 time 4 pv b1c3 b8c6 a1b1 d7d6
info multipv 1 depth 4 seldepth 5 score cp -28 nodes 450 nps 90000 time 5 pv g1h3 e7e5 d2d3 b8c6
info multipv 1 depth 4 seldepth 5 score cp -26 nodes 670 nps 95714 time 7 pv g2g3 e7e6 d2d3 b8c6
info multipv 1 depth 4 seldepth 9 score cp 8 nodes 1020 nps 85000 time 12 pv c2c4 a7a5 d2d3 e7e6
info multipv 1 depth 4 seldepth 9 score cp 52 nodes 1178 nps 84142 time 14 pv d2d4 a7a5 g1f3 e7e6
info depth 5
info multipv 1 depth 5 seldepth 5 score cp 44 upperbound nodes 1421 nps 88812 time 16 pv d2d4
info multipv 1 depth 5 seldepth 6 score cp 36 upperbound nodes 1577 nps 92764 time 17 pv d2d4
info multipv 1 depth 5 seldepth 7 score cp 36 nodes 1702 nps 89578 time 19 pv d2d4 b8c6 g1f3 e7e6 b1c3
info depth 6
info multipv 1 depth 6 seldepth 9 score cp 42 nodes 2289 nps 81750 time 28 pv d2d4 d7d5 g1f3 b8c6 e2e3 e7e6
info depth 7
info multipv 1 depth 7 seldepth 9 score cp 34 upperbound nodes 3733 nps 93325 time 40 pv d2d4
info multipv 1 depth 7 seldepth 15 score cp 26 upperbound nodes 4696 nps 99914 time 47 pv d2d4
info multipv 1 depth 7 seldepth 12 score cp 14 upperbound nodes 5602 nps 107730 time 52 pv d2d4
info multipv 1 depth 7 seldepth 12 score cp 10 nodes 5999 nps 109072 time 55 pv d2d4 d7d5 g1f3 g8f6 e2e3 e7e6 f1e2
info depth 8
info multipv 1 depth 8 seldepth 12 score cp 5 nodes 7937 nps 113385 time 70 pv d2d4 d7d5 g1f3 g8f6 c1f4 e7e6 e2e3 b8c6
info multipv 1 depth 8 seldepth 13 score cp 9 nodes 9728 nps 114447 time 85 pv g1f3 g8f6 e2e4 d7d6 d2d3 e7e5 d3d4 e5d4 d1d4
info depth 9
info multipv 1 depth 9 seldepth 17 score cp 17 lowerbound nodes 14264 nps 114112 time 125 pv g1f3
info multipv 1 depth 9 seldepth 15 score cp 25 lowerbound nodes 16522 nps 116352 time 142 pv g1f3
info multipv 1 depth 9 seldepth 10 score cp 26 nodes 16932 nps 117583 time 144 pv g1f3 g8f6 d2d4 d7d5 e2e3 e7e6 f1d3
info depth 10
info multipv 1 depth 10 seldepth 20 score cp 34 lowerbound nodes 46005 nps 132962 time 346 pv e2e4
info multipv 1 depth 10 seldepth 20 score cp 38 nodes 51149 nps 134957 time 379 pv e2e4 d7d6 d2d4 g8f6 b1c3 e7e5 g1f3 b8c6 d4e5 c6e5
info depth 11
info multipv 1 depth 11 seldepth 22 score cp 30 upperbound nodes 83804 nps 141322 time 593 pv e2e4
info multipv 1 depth 11 seldepth 19 score cp 38 nodes 101680 nps 143211 time 710 pv e2e4 e7e5 b1c3 g8f6 f1c4 b8c6 d2d3 d7d6 g1f3 c6a5
info depth 12
info multipv 1 depth 12 seldepth 22 score cp 30 upperbound nodes 129847 nps 144756 time 897 pv e2e4
info multipv 1 depth 12 seldepth 20 score cp 22 nodes 143542 nps 145432 time 987 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 b1c3 f8b4 d4c6 d7c6 d1d8 e8d8
info hashfull 851 tbhits 0 nodes 145993 nps 145847
info depth 13
info multipv 1 depth 13 seldepth 22 score cp 30 lowerbound nodes 197119 nps 145690 time 1353 pv e2e4
info multipv 1 depth 13 seldepth 20 score cp 32 nodes 209328 nps 146485 time 1429 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 b1c3 f8b4 d4c6 b4c3 b2c3 d7c6 d1d8 e8d8
bestmove 0000

**Comment by Alexei1981** [comment]
But the result of the previous version of Vajolet2-2.4:

$ Vajolet2-2.4-arm64v8
Vajolet2 2.4 by Marco Belli
go depth 13
info depth 1
info multipv 1 depth 1 seldepth 1 score cp 41 nodes 24 nps 24000 time 1 pv d2d3
info depth 2
info multipv 1 depth 2 seldepth 2 score cp 4 nodes 49 nps 24500 time 2 pv d2d3 e7e6
info depth 3
info multipv 1 depth 3 seldepth 7 score cp 38 nodes 241 nps 48200 time 5 pv d2d3 e7e6 g1f3
info depth 4
info multipv 1 depth 4 seldepth 8 score cp 13 nodes 433 nps 61857 time 7 pv d2d3 e7e6 g1f3 g8f6
info depth 5
info multipv 1 depth 5 seldepth 9 score cp 22 lowerbound nodes 706 nps 58833 time 12 pv d2d3
info multipv 1 depth 5 seldepth 5 score cp 26 nodes 809 nps 67416 time 12 pv d2d3 e7e6 g1f3 b8c6 c2c4
info depth 6
info multipv 1 depth 6 seldepth 8 score cp 18 upperbound nodes 1230 nps 49200 time 25 pv d2d3
info multipv 1 depth 6 seldepth 8 score cp 15 nodes 1569 nps 56035 time 28 pv d2d3 e7e6 g1f3 b8c6 e2e4 g8f6
info depth 7
info multipv 1 depth 7 seldepth 14 score cp 23 lowerbound nodes 6928 nps 89974 time 77 pv e2e4
info multipv 1 depth 7 seldepth 12 score cp 7 upperbound nodes 8015 nps 93197 time 86 pv e2e4
info multipv 1 depth 7 seldepth 14 score cp 28 nodes 10208 nps 96301 time 106 pv e2e4 d7d5 e4d5 g8f6 g1f3 d8d5 d2d3
info depth 8
info multipv 1 depth 8 seldepth 16 score cp 20 upperbound nodes 14918 nps 106557 time 140 pv e2e4
info multipv 1 depth 8 seldepth 16 score cp 19 nodes 17273 nps 112162 time 154 pv e2e4 d7d6 d2d4 g8f6 b1c3 e7e5 g1f3 b8c6
info depth 9
info multipv 1 depth 9 seldepth 18 score cp 18 nodes 21851 nps 118113 time 185 pv e2e4 d7d6 d2d4 g8f6 b1c3 e7e5 g1f3 b8c6 d4e5 c6e5
info depth 10
info multipv 1 depth 10 seldepth 19 score cp 26 lowerbound nodes 28732 nps 123313 time 233 pv e2e4
info multipv 1 depth 10 seldepth 19 score cp 20 nodes 35337 nps 128498 time 275 pv e2e4 e7e6 d2d4 g8f6 e4e5 f6e4 g1f3 d7d5 f1e2
info depth 11
info multipv 1 depth 11 seldepth 23 score cp 12 upperbound nodes 82853 nps 136271 time 608 pv e2e4
info multipv 1 depth 11 seldepth 21 score cp 28 lowerbound nodes 95093 nps 136824 time 695 pv e2e4
info multipv 1 depth 11 seldepth 19 score cp 24 nodes 96219 nps 137455 time 700 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 d4c6 d7c6 d1d8 e8d8
info depth 12
info hashfull 955 tbhits 0 nodes 140192 nps 139633
info multipv 1 depth 12 seldepth 22 score cp 32 lowerbound nodes 148182 nps 139007 time 1066 pv e2e4
info multipv 1 depth 12 seldepth 22 score cp 16 upperbound nodes 155334 nps 138443 time 1122 pv e2e4
info multipv 1 depth 12 seldepth 23 score cp 26 nodes 164696 nps 137590 time 1197 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 b1c3 f8b4 f2f3 e8g8 d4c6 b4c3 b2c3 b7c6
info depth 13
info multipv 1 depth 13 seldepth 23 score cp 26 nodes 242095 nps 136854 time 1769 pv e2e4 e7e5 g1f3 b8c6 d2d4 e5d4 f3d4 g8f6 b1c3 f8b4 f2f3 a7a6 a2a4 b4c5 c1e3
bestmove e2e4 ponder e7e5

**Comment by Alexei1981** [comment]
Everything, I solved the problem. I put instead of the optimization flag -O3, the -O2 flag and everything worked. Strange that aggressive optimization gave such a negative effect.

**Comment by elcabesa** [comment]
what compiler are you using? I had some problem on SEE() function with GCC 7.2... solved using previous versions

**Comment by Alexei1981** [comment]
I used GCC-7.2 too. But I say, the problem disappeared as soon as I did less aggressive optimization (O2), now the engines work well.

**Comment by elcabesa** [comment]
I had big problems with gcc 7.2. I'm now using 6.4.0 waiting for a new version of gcc :)

**Comment by Alexei1981** [comment]
Я использую GCC-7.2. потому что на андроиде он дал + 10-12% производительности.
Есть ещё вопрос: Я пробовал запускать benchmark для создания PGO версии,но не получилось.Когда я делаю stockfish на андроид,то компилирую сначала версию как обычно с флагами(--fprofile-generate и -lgcov),затем через терминал даю команду [bench] и движок генерирует файлы .gcda .Хорошо бы чтобы у Vajolet2 тоже так было бы.

**Comment by Alexei1981** [comment]
I'm using GCC-7.2. because on the android he gave + 10-12% of the performance.
There is another question: I tried to run a benchmark to create a PGO version, but it did not work out. When I make stockfish on an android, I compile the version as usual with the flags (-fprofile-generate and -lgcov), then through the terminal I give the command [bench ] and the engine generates .gcda files. It would be nice to have Vajolet2 do it too.
